import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";

const GLOBAL_JURISDICTIONS = [
  {
    countryCode: "NG",
    name: "Nigeria",
    legalSystem: "Common Law / Customary / Islamic",
    landRegistrationSystem: "Deeds & Title Registration (State Registries)",
    currency: "NGN",
    timezone: "Africa/Lagos",
    supportLevel: "LEVEL_3",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: true,
    commonDocuments: [
      "Survey Plan",
      "Deed of Assignment",
      "Certificate of Occupancy (C of O)",
      "Governor's Consent",
      "Government Gazette Excision",
    ],
  },
  {
    countryCode: "GB",
    name: "United Kingdom",
    legalSystem: "Common Law",
    landRegistrationSystem: "HM Land Registry (Title Register & Title Plan)",
    currency: "GBP",
    timezone: "Europe/London",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Official Copy of Register", "Title Plan", "TR1 Transfer Deed"],
  },
  {
    countryCode: "US",
    name: "United States",
    legalSystem: "Common Law",
    landRegistrationSystem: "County Recorder Deeds & Title Insurance",
    currency: "USD",
    timezone: "America/New_York",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Warranty Deed", "Quitclaim Deed", "Plat Map", "Title Commitment"],
  },
  {
    countryCode: "CA",
    name: "Canada",
    legalSystem: "Common Law / Civil Law (Quebec)",
    landRegistrationSystem: "Land Titles / Registry System (Teranet)",
    currency: "CAD",
    timezone: "America/Toronto",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Transfer / Deed of Land", "Surveyors Real Property Report"],
  },
  {
    countryCode: "KE",
    name: "Kenya",
    legalSystem: "Common Law",
    landRegistrationSystem: "ArdhiSasa Digital Land Registry",
    currency: "KES",
    timezone: "Africa/Nairobi",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Certificate of Title", "Deed Plan", "Official Search Certificate"],
  },
  {
    countryCode: "GH",
    name: "Ghana",
    legalSystem: "Common Law / Customary",
    landRegistrationSystem: "Lands Commission (Title & Deeds)",
    currency: "GHS",
    timezone: "Africa/Accra",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Indenture", "Cadastral Plan", "Land Title Certificate"],
  },
  {
    countryCode: "ZA",
    name: "South Africa",
    legalSystem: "Roman-Dutch / Common Law",
    landRegistrationSystem: "Deeds Registries (Deeds Office)",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Title Deed", "Surveyor-General Diagram"],
  },
  {
    countryCode: "AE",
    name: "United Arab Emirates",
    legalSystem: "Civil Law / Sharia",
    landRegistrationSystem: "Dubai Land Department (DLD) / Municipal Registries",
    currency: "AED",
    timezone: "Asia/Dubai",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Title Deed Certificate", "Oqood Initial Contract", "Site Plan"],
  },
  {
    countryCode: "AU",
    name: "Australia",
    legalSystem: "Common Law",
    landRegistrationSystem: "Torrens Title System (State Land Titles Offices)",
    currency: "AUD",
    timezone: "Australia/Sydney",
    supportLevel: "LEVEL_2",
    documentAnalysis: true,
    externalVerification: true,
    geospatialAnalysis: true,
    professionalVerification: false,
    commonDocuments: ["Certificate of Title", "Deposited Plan (DP)", "Transfer Dealing"],
  },
];

export async function GET(request: NextRequest) {
  const requestId = randomUUID();
  const { pathname } = new URL(request.url);

  return NextResponse.json({
    data: GLOBAL_JURISDICTIONS,
    meta: {
      requestId,
      total: GLOBAL_JURISDICTIONS.length,
    },
  });
}
